In [1]:
import numpy as np

In [4]:
a=np.zeros(20)
a[3]=5
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
array_master =np.ones(20)

array_copy=array_master.copy()
array_copy


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [8]:
array = np.ones(30)

array[:]=100
array


array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [10]:
array1=np.arange(21,32)
array2=np.arange(11,22)
array1-array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [11]:
a1=np.arange(2,11,2)
a2=np.arange(22,31,2)
np.stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [12]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [15]:
array_matrix=np.arange(30).reshape(5,6)
array_matrix[1,2]

8

In [19]:
array=np.eye(10)
array[array==0]=21
array

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [21]:
a=np.random.rand(10)
a>0.2
a

array([0.32302847, 0.74439696, 0.26998127, 0.03078847, 0.7807419 ,
       0.58870265, 0.84049419, 0.01048818, 0.5430026 , 0.29044518])

In [22]:
np.random.randn(5,2)

array([[-1.17084629,  0.25089316],
       [-0.51708924, -0.64777837],
       [-0.609843  , -1.60421621],
       [-0.32108518,  0.59442542],
       [ 1.69785423,  0.19695887]])

In [24]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [25]:
mat = np.arange(1,101).reshape(10,10)
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
mat[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

In [27]:
mat[5,4]

55

In [29]:
mat[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [31]:
mat[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [32]:
mat[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [33]:
mat.sum()

5050

In [34]:
mat.std()

28.86607004772212

In [35]:
mat.var()

833.25

In [36]:
mat.mean()

50.5

In [37]:
mat.max()

100

In [38]:
mat.min()

1